# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: hotsoon(火山极速版)

on:
  workflow_dispatch:
  schedule:
     - cron: '0 7-23/2 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      HOTSOONSIGNHEADER : ${{ secrets.HOTSOONSIGNHEADER  }}
      HOTSOONSIGNKEY : ${{ secrets.HOTSOONSIGNKEY  }}
      BBB_CK1: ${{ secrets.BBB_CK1 }}
      BBB_CK2: ${{ secrets.BBB_CK2 }}
      BBB_CK3: ${{ secrets.BBB_CK3 }}
      BBB_CK4: ${{ secrets.BBB_CK4 }}
      BBB_CK5: ${{ secrets.BBB_CK5 }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.HOTSOONSIGNHEADER
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【B】'
        if: env.HOTSOONSIGNHEADER         
        run: |
          cd ~/Scripts
          node Task/hotsoon.js
        env:
          HOTSOONSIGNHEADER : ${{ secrets.HOTSOONSIGNHEADER  }}
          HOTSOONSIGNKEY : ${{ secrets.HOTSOONSIGNKEY  }}
          


